package com.company.entity;

public class DicNative {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_native.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_native.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_native.parent_code
     *
     * @mbggenerated
     */
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_native.mainlevel
     *
     * @mbggenerated
     */
    private String mainlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_native.levelId
     *
     * @mbggenerated
     */
    private Integer levelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_native.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_native.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_native.ordernum
     *
     * @mbggenerated
     */
    private Integer ordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_native.firstWord
     *
     * @mbggenerated
     */
    private String firstword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_native.abb
     *
     * @mbggenerated
     */
    private String abb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_native.pinyin
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_native.code
     *
     * @return the value of dic_native.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_native.code
     *
     * @param code the value for dic_native.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_native.name
     *
     * @return the value of dic_native.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_native.name
     *
     * @param name the value for dic_native.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_native.parent_code
     *
     * @return the value of dic_native.parent_code
     *
     * @mbggenerated
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_native.parent_code
     *
     * @param parentCode the value for dic_native.parent_code
     *
     * @mbggenerated
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_native.mainlevel
     *
     * @return the value of dic_native.mainlevel
     *
     * @mbggenerated
     */
    public String getMainlevel() {
        return mainlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_native.mainlevel
     *
     * @param mainlevel the value for dic_native.mainlevel
     *
     * @mbggenerated
     */
    public void setMainlevel(String mainlevel) {
        this.mainlevel = mainlevel == null ? null : mainlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_native.levelId
     *
     * @return the value of dic_native.levelId
     *
     * @mbggenerated
     */
    public Integer getLevelid() {
        return levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_native.levelId
     *
     * @param levelid the value for dic_native.levelId
     *
     * @mbggenerated
     */
    public void setLevelid(Integer levelid) {
        this.levelid = levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_native.latitude
     *
     * @return the value of dic_native.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_native.latitude
     *
     * @param latitude the value for dic_native.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_native.longitude
     *
     * @return the value of dic_native.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_native.longitude
     *
     * @param longitude the value for dic_native.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_native.ordernum
     *
     * @return the value of dic_native.ordernum
     *
     * @mbggenerated
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_native.ordernum
     *
     * @param ordernum the value for dic_native.ordernum
     *
     * @mbggenerated
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_native.firstWord
     *
     * @return the value of dic_native.firstWord
     *
     * @mbggenerated
     */
    public String getFirstword() {
        return firstword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_native.firstWord
     *
     * @param firstword the value for dic_native.firstWord
     *
     * @mbggenerated
     */
    public void setFirstword(String firstword) {
        this.firstword = firstword == null ? null : firstword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_native.abb
     *
     * @return the value of dic_native.abb
     *
     * @mbggenerated
     */
    public String getAbb() {
        return abb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_native.abb
     *
     * @param abb the value for dic_native.abb
     *
     * @mbggenerated
     */
    public void setAbb(String abb) {
        this.abb = abb == null ? null : abb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_native.pinyin
     *
     * @return the value of dic_native.pinyin
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_native.pinyin
     *
     * @param pinyin the value for dic_native.pinyin
     *
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }
}