package com.company.mapper;

import com.company.entity.DicNative;

public interface DicNativeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_native
     *
     * @mbggenerated
     */
    int insert(DicNative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_native
     *
     * @mbggenerated
     */
    int insertSelective(DicNative record);
}